require 'rubygems'
require 'airake'

ENV["AIRAKE_ROOT"] = File.dirname(__FILE__)
ENV["AIRAKE_ENV"] = "development"

# Aliases
task :test => [ "air:test" ] do; end
task :compile => [ "flex:compile" ] do; end
task :clean => [ "flex:clean" ] do; end
